### PR TITLE
Remove MAX_CALLS_ALLOWED restriction - Closes #35

### LINKED ISSUE #35: No more than 100 calls allowed for a procedure
#If we try to make more than 100 RPC calls for the same procedure in a short time, it sends back an error 'No more than 100 calls allowed for a procedure'.

This happens when we call rpc.status on more than 100 peers in a short time and causes us to disconnect from peers arbitrarily.

Although it is a good thing to not have more than about 100 peers at any given time, this is not a good disconnection strategy (especially since the top 100 list in this case is not shuffled). If we don't want to allow more than 100 concurrent RPC calls, then this should be handled at a higher level in the logic.

### PR DESCRIPTION
**Pull request by jondubois**
This change fixes the block propagation issue in betanet.

### CODE REVIEW

**Review by 4miners — APPROVED** [review]

**Comment by nazarhussain** [comment]
@jondubois Shouldn't we increase the limit instead of removing it? As its a good safeguard. There never been unlimited resources on the server and such RPC calls consume some resources.

**Comment by jondubois** [comment]
@nazarhussain This limit is not useful because it's per-procedure (shared between all peers and not per-peer). So if you call the same procedure on multiple peers at the same time, they will add up and then some of your peers will not receive the RPC.

Also, we already have a timeout which will make sure that RPCs will be cleared from the `callsResolvers` object after a while so from a performance standpoint there is no need to artificially limit the number of calls down to a fixed number; if someone has a more powerful machine, their node should be allowed to make more calls per second.

**Review by nazarhussain — DISMISSED** [review]
Yes probably if a node have more resources removing this logic can let it call more rpc methods. But what if it have less then this logic will eat all resources.

Have you ever seen any low level library or framework which would be dealing with I/O and specially network I/O and don't have limit on it? Even DBs don't allow you to read unlimited due to disk I/O.

Probably increasing that limit to more optimal level and then handling the error in on app level is the better solution.

**Comment by shuse2** [comment]
I think adding the limitation at current state is pretty dangerous imo because error itself is not handle correctly, and it is hard to handle it from the app layer.
Also, i dont think this is a low level library, more like util file...=p
Moreover, it's RPC call, so it always has timeout if the node cannot handle it, it should be resolved by that.
it is not the connection itself but it's a number of call, so i dont think it make sense to limit it here.

**Review by shuse2 — APPROVED** [review]

**Comment by nazarhussain** [comment]
@shuse2 You think its a rpc call with a timeout so it will eventually fail if system don't have resources. What if the reset of the calls that our system keep pushing while there is no resources? Everything would be hanged up until timeout. 

Yes its a low level library, trying to extend websocket protocol with RPC feature. This library is not implementing a use case, that's what our app is doing. 

Lately I don't agree that its hard to handle error in our application correctly. There are other failure case in this library as well, are we not handling those as well?

**Comment by jondubois** [comment]
> Have you ever seen any low level library or framework which would be dealing with I/O and specially network I/O and don't have limit on it? Even DBs don't allow you to read unlimited due to disk I/O.

@nazarhussain There is a limit in this case but it's a time limit. Our timeout is 2 seconds so the limit is however many RPCs the node can perform within this 2 second timeframe. If the node tries to send too many (more than it can process) then they will all start timing out. But ideally our algorithm should be smart enough to not get into such a situation to begin with.

**Pull request merged**
