### PR TITLE
Register RPC functions on slave processes - Closes #2

### LINKED ISSUE #2: Missing unit tests for SlaveWAMPServer
Unit tests and jsdocs are missing in mentioned file.

### PR DESCRIPTION
**Pull request by MaciejBaj**
Add possibility to register RPC functions which can be assigned to slave processes.

Closes #2

### CODE REVIEW

**Comment by jondubois** [comment]
When running the tests, I still get the issue `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): No more than 100 calls allowed`.

**Comment by jondubois** [comment]
Node.js `v7.10.0`

**Comment by Isabello** [comment]
I have the same issue on `node v6.11.1`

**Comment by MaciejBaj** [comment]
the issue is targeted by different PR - https://github.com/LiskHQ/wamp-socket-cluster/pull/10

**Comment by jondubois** [comment]
:+1:

**Comment by jondubois** [comment]
It looks like the RPC response from master is not being tested. It may be worthwhile to write a test for this part of the code: https://github.com/LiskHQ/wamp-socket-cluster/blob/ec862aa707f0464d0012f1e7645a63fddcd2dbf4/SlaveWAMPServer.js#L27

**Comment by MaciejBaj** [comment]
yes thanks, valid points. SlaveWAMPServer has missing tests which is also addressed by another issue: #2

**Pull request merged**
